// <auto-generated />
using System;
using ApiSimulador.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSimulador.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20250821171934_NoMigration2")]
    partial class NoMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiSimulador.Models.Parcela", b =>
                {
                    b.Property<int>("CO_PARCELA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CO_PARCELA"));

                    b.Property<int>("CO_SIMULACAO")
                        .HasColumnType("int");

                    b.Property<short>("NU_PARCELA")
                        .HasColumnType("smallint")
                        .HasAnnotation("Relational:JsonPropertyName", "numero");

                    b.Property<int>("SimulacaoCO_SIMULACAO")
                        .HasColumnType("int");

                    b.Property<string>("TP_AMORTIZACAO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("VR_AMORTIZACAO")
                        .HasColumnType("decimal(18, 2)")
                        .HasAnnotation("Relational:JsonPropertyName", "valorAmortizacao");

                    b.Property<decimal>("VR_JUROS")
                        .HasColumnType("decimal(18, 2)")
                        .HasAnnotation("Relational:JsonPropertyName", "valorJuros");

                    b.Property<decimal>("VR_PRESTACAO")
                        .HasColumnType("decimal(18, 2)")
                        .HasAnnotation("Relational:JsonPropertyName", "valorPrestacao");

                    b.HasKey("CO_PARCELA");

                    b.HasIndex("SimulacaoCO_SIMULACAO");

                    b.ToTable("PARCELA");
                });

            modelBuilder.Entity("ApiSimulador.Models.Simulacao", b =>
                {
                    b.Property<int>("CO_SIMULACAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CO_SIMULACAO"));

                    b.Property<DateTime>("DT_SIMULACAO")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PC_TAXA_JUROS")
                        .HasColumnType("decimal(10, 9)");

                    b.Property<short>("PZ_SIMULACAO")
                        .HasColumnType("smallint");

                    b.Property<decimal>("VR_SIMULACAO")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CO_SIMULACAO");

                    b.ToTable("SIMULACAO");
                });

            modelBuilder.Entity("ApiSimulador.Models.Parcela", b =>
                {
                    b.HasOne("ApiSimulador.Models.Simulacao", "Simulacao")
                        .WithMany("Parcelas")
                        .HasForeignKey("SimulacaoCO_SIMULACAO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("ApiSimulador.Models.Simulacao", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
