// <auto-generated />
using ApiSimulador.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSimulador.Migrations.SqlServerDb
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiSimulador.Models.Produto", b =>
                {
                    b.Property<int>("CO_PRODUTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CO_PRODUTO"));

                    b.Property<string>("NO_PRODUTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("NU_MAXIMO_MESES")
                        .HasColumnType("smallint");

                    b.Property<short>("NU_MINIMO_MESES")
                        .HasColumnType("smallint");

                    b.Property<decimal>("PC_TAXA_JUROS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VR_MAXIMO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VR_MINIMO")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CO_PRODUTO");

                    b.ToTable("PRODUTO");
                });
#pragma warning restore 612, 618
        }
    }
}
